# An example YAML settings file for mini GW toy simulations

# number of cores to use in parallel
ncores: 52

output_filename: gw_toy_results_log.csv

zeniths:
  - 20
  - 40
  - 60

grbsens_files:
  north:
    20: grbsens-5.0sigma_t1s-t16384s_irf-North_z20_0.5h.txt
    40: grbsens-5.0sigma_t1s-t16384s_irf-North_z40_0.5h.txt
    60: grbsens-5.0sigma_t1s-t16384s_irf-North_z60_0.5h.txt
  south:
    20: grbsens-5.0sigma_t1s-t16384s_irf-South_z20_0.5h.txt
    40: grbsens-5.0sigma_t1s-t16384s_irf-South_z40_0.5h.txt
    60: grbsens-5.0sigma_t1s-t16384s_irf-South_z60_0.5h.txt

bns_file: "/astri01/data1/gershon/gw_toy/gw_toy/BNS-GW-Time_onAxis5deg-original.txt"
first_index: null  # set to null to ignore
last_index: null   # set to null to ignore
precision: 2  # number of decimal places to calculate for each observation time

time_delays:  # in seconds
# log scale from 10s to 24h (50 bins)
  - 10
  - 12
  - 14
  - 17
  - 21
  - 25
  - 30
  - 37
  - 44
  - 53
  - 64
  - 77
  - 92
  - 111
  - 133
  - 160
  - 193
  - 232
  - 279
  - 336
  - 404
  - 486
  - 585
  - 704
  - 847
  - 1020
  - 1227
  - 1476
  - 1776
  - 2137
  - 2571
  - 3093
  - 3722
  - 4478
  - 5388
  - 6483
  - 7801
  - 9386
  - 11293
  - 13588
  - 16349
  - 19671
  - 23668
  - 28477
  - 34263
  - 41225
  - 49602
  - 59681
  - 71809
  - 86400

# original list
#  - 1
#  - 10
#  - 30
#  - 60
#  - 90
#  - 120       # 2m
#  - 300       # 5m
#  - 600       # 10m
#  - 3600      # 1h
#  - 7200      # 2h
#  - 14400     # 4h
#  - 28800     # 8h
#  - 43200     # 12h
#  - 64800     # 18h
#  - 86400     # 24h
