# An example YAML settings file for plotting results from GWToy.py

# the output file from GWToy.py, csv or pkl
input_file: gw_toy_results_log.pkl

output_directory: plots

color_scheme: YlGnBu

show_percents: False

log_scale: True
min_value: 0
max_value: 90

sites:
  # - North
  - South

zeniths:
  - 20
  - 40
  - 60
  - all

x_tick_labels:
  - "10s"
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - "30s"
  - ""
  - ""
  - ""
  - "1m"
  - ""
  - ""
  - ""
  - "2m"
  - ""
  - ""
  - ""
  - ""
  - ""
  - "5m"
  - ""
  - ""
  - ""
  - "10m"
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - "30m"
  - ""
  - ""
  - ""
  - "1h"
  - ""
  - ""
  - ""
  - ""
  - "2h"
  - ""
  - ""
  - ""
  - "4h"
  - ""
  - ""
  - ""
  - "8h"

y_tick_labels:
  - "10s"
  - ""
  - ""
  - ""
  - ""
  - ""
  - "30s"
  - ""
  - ""
  - ""
  - "1m"
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - "5m"
  - ""
  - ""
  - ""
  - ""
  - ""
  - "15m"
  - ""
  - ""
  - ""
  - "30m"
  - ""
  - ""
  - ""
  - "1h"
  - ""
  - ""
  - ""
  - "2h"
  - ""
  - ""
  - "4h"
  - ""
  - ""
  - ""
  - "8h"
  - ""
  - "12hr"
  - ""
  - "18hr"
  - ""
  - "24h"

observation_times:
# log scale from 10s to 8h (50 bins)
  - 10
  - 12
  - 14
  - 16
  - 19
  - 23
  - 27
  - 31
  - 37
  - 43
  - 51
  - 60
  - 70
  - 83
  - 97
  - 115
  - 135
  - 159
  - 187
  - 219
  - 258
  - 304
  - 357
  - 421
  - 495
  - 582
  - 685
  - 806
  - 948
  - 1115
  - 1312
  - 1544
  - 1816
  - 2137
  - 2514
  - 2958
  - 3480
  - 4094
  - 4817
  - 5668
  - 6668
  - 7845
  - 9230
  - 10859
  - 12776
  - 15031
  - 17685
  - 20806
  - 24479
  - 28800

# # in seconds, recall time delays are fixed in the GWToy output
#   - 10
#   - 30
#   - 60
#   - 90
#   - 120       # 2m
#   - 300       # 5m
#   - 600       # 10m
#   - 3600      # 1h
#   - 7200      # 2h
#   - 14400     # 4h
#   - 28800     # 8h
#   - 43200     # 12h
#   - 64800     # 18h
#   - 86400     # 24h