# An example YAML settings file for plotting results from GWToy.py

# the output file from GWToy.py, csv or pkl
input_file: gw_toy_results_new.pkl

output_directory: plots

sites:
  - North
  - South

zeniths:
  - 20
  - 40
  - 60

observation_times:
# in seconds, recall time delays are fixed in the GWToy output
  - 10
  - 30
  - 60
  - 90
  - 120       # 2m
  - 300       # 5m
  - 600       # 10m
  - 3600      # 1h
  - 7200      # 2h
  - 14400     # 4h
  - 28800     # 8h
  - 43200     # 12h
  - 64800     # 18h
  - 86400     # 24h